"""The Stern-Brocot tree, the Farey sequence, and Stern's diatomic series.

Three views of the same object -- an exact enumeration of the positive
rationals, each in lowest terms, each appearing exactly once:

* **Stern-Brocot tree.** Start from the boundary "fractions" ``0/1`` and ``1/0``
  and repeatedly insert *mediants*. Every positive rational is a node, and the
  path to it (a string of ``L``/``R`` turns) is nothing but its continued
  fraction read off as run lengths -- :func:`rational_to_path` and
  :func:`path_to_rational` are the two directions of that dictionary.
* **Farey sequences.** ``F_n`` lists the rationals in ``[0, 1]`` with
  denominator ``<= n`` in order; neighbours ``a/b < c/d`` always satisfy the
  unimodular relation ``b*c - a*d == 1``.
* **Stern's diatomic sequence** (``fusc``) enumerates the tree breadth-first:
  consecutive values ``fusc(n)/fusc(n+1)`` are the Calkin-Wilf ordering of the
  positive rationals.

Everything here is exact integer / :class:`~fractions.Fraction` arithmetic.
"""

from __future__ import annotations

from fractions import Fraction
from typing import Iterator

from ..cf.expand import cf_from_fraction

__all__ = [
    "mediant",
    "rational_to_path",
    "path_to_rational",
    "farey",
    "farey_length",
    "fusc",
    "calkin_wilf",
    "stern_brocot_bfs",
]


def mediant(a: Fraction, b: Fraction) -> Fraction:
    """The mediant ``(a.num + b.num) / (a.den + b.den)`` of two fractions.

    The mediant always lies strictly between its parents. On adjacent
    Stern-Brocot / Farey fractions it is automatically in lowest terms.

    >>> mediant(Fraction(1, 2), Fraction(1, 1))
    Fraction(2, 3)
    >>> mediant(Fraction(0, 1), Fraction(1, 1))
    Fraction(1, 2)
    """
    return Fraction(
        a.numerator + b.numerator,
        a.denominator + b.denominator,
    )


def rational_to_path(x: Fraction) -> str:
    """The Stern-Brocot address of a positive rational as an ``L``/``R`` string.

    Derived from the continued fraction ``x = [a0; a1, a2, ...]``: the address
    is ``"R" * a0 + "L" * a1 + "R" * a2 + ...`` with the final run shortened by
    one, since the last turn lands *on* the node rather than passing it. The
    root ``1/1`` has the empty address.

    >>> rational_to_path(Fraction(1, 1))
    ''
    >>> rational_to_path(Fraction(3, 2))
    'RL'
    >>> rational_to_path(Fraction(2, 3))
    'LR'
    >>> rational_to_path(Fraction(5, 3))
    'RLR'
    """
    if x <= 0:
        raise ValueError("Stern-Brocot addresses are defined for x > 0")
    letters = "RL"
    address = "".join(
        letters[i % 2] * a for i, a in enumerate(cf_from_fraction(x))
    )
    return address[:-1]  # drop the final step: it lands on the node itself


def path_to_rational(path: str) -> Fraction:
    """The positive rational at a Stern-Brocot address (inverse of the above).

    Walk down from the root, narrowing the bracket ``left < node < right`` (kept
    as ``(num, den)`` pairs so the boundary ``1/0`` stays representable): an
    ``R`` replaces the left bound with the current mediant, an ``L`` the right.
    The node is the final mediant.

    >>> path_to_rational('')
    Fraction(1, 1)
    >>> path_to_rational('RL')
    Fraction(3, 2)
    >>> path_to_rational(rational_to_path(Fraction(22, 7))) == Fraction(22, 7)
    True
    """
    left = (0, 1)   # 0/1
    right = (1, 0)  # 1/0, the "infinity" boundary
    for ch in path:
        m = (left[0] + right[0], left[1] + right[1])
        if ch == "R":
            left = m
        elif ch == "L":
            right = m
        else:
            raise ValueError(f"path must be over 'L'/'R', got {ch!r}")
    return Fraction(left[0] + right[0], left[1] + right[1])


def farey(n: int) -> Iterator[Fraction]:
    """The Farey sequence ``F_n``: reduced fractions in ``[0, 1]``, ascending.

    Generated by the classic next-term recurrence, which produces each term in
    lowest terms without ever sorting or de-duplicating.

    >>> [str(f) for f in farey(5)]
    ['0', '1/5', '1/4', '1/3', '2/5', '1/2', '3/5', '2/3', '3/4', '4/5', '1']
    """
    if n < 1:
        raise ValueError("Farey order n must be >= 1")
    a, b, c, d = 0, 1, 1, n
    yield Fraction(a, b)
    while c <= n:
        k = (n + b) // d
        a, b, c, d = c, d, k * c - a, k * d - b
        yield Fraction(a, b)


def _totient(n: int) -> int:
    """Euler's totient ``phi(n)`` by trial-division factoring.

    >>> [_totient(n) for n in range(1, 8)]
    [1, 1, 2, 2, 4, 2, 6]
    """
    if n < 1:
        raise ValueError("totient needs n >= 1")
    result = n
    m = n
    p = 2
    while p * p <= m:
        if m % p == 0:
            while m % p == 0:
                m //= p
            result -= result // p
        p += 1
    if m > 1:
        result -= result // m
    return result


def farey_length(n: int) -> int:
    """The number of terms in ``F_n``, i.e. ``1 + sum(phi(k) for k in 1..n)``.

    Counted from Euler's totient rather than by enumerating the sequence.

    >>> [farey_length(n) for n in range(1, 8)]
    [2, 3, 5, 7, 11, 13, 19]
    """
    if n < 1:
        raise ValueError("Farey order n must be >= 1")
    return 1 + sum(_totient(k) for k in range(1, n + 1))


def fusc(n: int) -> int:
    """Stern's diatomic sequence ``fusc(n)`` computed iteratively over the bits.

    Satisfies ``fusc(0)=0``, ``fusc(1)=1``, ``fusc(2n)=fusc(n)`` and
    ``fusc(2n+1)=fusc(n)+fusc(n+1)`` -- but this evaluation folds the bits of
    ``n`` in a single pass, with no recursion.

    >>> [fusc(n) for n in range(11)]
    [0, 1, 1, 2, 1, 3, 2, 3, 1, 4, 3]
    """
    if n < 0:
        raise ValueError("fusc is defined for n >= 0")
    a, b = 1, 0
    while n > 0:
        if n & 1:
            b += a
        else:
            a += b
        n >>= 1
    return b


def calkin_wilf(limit: int | None = None) -> Iterator[Fraction]:
    """The Calkin-Wilf enumeration of the positive rationals, each once.

    Uses Newman's successor map ``x -> 1 / (2*floor(x) + 1 - x)`` starting at
    ``1``; the resulting fractions are automatically in lowest terms and equal
    ``fusc(n)/fusc(n+1)`` for ``n = 1, 2, 3, ...``. Stops after ``limit`` terms
    if given, otherwise runs forever.

    >>> list(calkin_wilf(6))
    [Fraction(1, 1), Fraction(1, 2), Fraction(2, 1), Fraction(1, 3), Fraction(3, 2), Fraction(2, 3)]
    """
    x = Fraction(1)
    count = 0
    while limit is None or count < limit:
        yield x
        count += 1
        floor = x.numerator // x.denominator  # x > 0, so this is the floor
        x = 1 / (2 * floor + 1 - x)


def stern_brocot_bfs(depth: int) -> Iterator[Fraction]:
    """Breadth-first enumeration of the Stern-Brocot tree to ``depth`` levels.

    Level 0 is the root ``1/1``; each node yields its two child mediants at the
    next level. ``depth`` counts levels emitted (``depth=0`` yields nothing).

    >>> list(stern_brocot_bfs(3))
    [Fraction(1, 1), Fraction(1, 2), Fraction(2, 1), Fraction(1, 3), Fraction(2, 3), Fraction(3, 2), Fraction(3, 1)]
    """
    if depth < 0:
        raise ValueError("depth must be >= 0")
    level = [((0, 1), (1, 0))]  # (left, right) brackets, root bracket first
    for _ in range(depth):
        nxt: list[tuple[tuple[int, int], tuple[int, int]]] = []
        for left, right in level:
            m = (left[0] + right[0], left[1] + right[1])
            yield Fraction(m[0], m[1])
            nxt.append((left, m))
            nxt.append((m, right))
        level = nxt
