"""The Markov spectrum: the numbers that come *after* the golden ratio.

The Golden Milestone taught that ``phi`` is the hardest number to approximate,
with Hurwitz's constant ``sqrt(5)``. But what is *second*-hardest? The answer is
a discrete, beautiful ladder — the **Lagrange spectrum** below 3 — governed by
the solutions of the Markov equation

    x^2 + y^2 + z^2 = 3*x*y*z.

Its positive solutions (**Markov triples**) grow from ``(1, 1, 1)`` by "Vieta
jumping": fixing two coordinates, the third satisfies a quadratic with a second
integer root. The largest entries are the **Markov numbers** 1, 2, 5, 13, 29,
34, 89, ...; each ``m`` yields a **Lagrange number** ``L_m = sqrt(9*m^2 - 4)/m``,
and these are exactly the spectrum below 3:

    sqrt(5) < sqrt(8) < sqrt(221)/5 < sqrt(1517)/13 < ... -> 3.

The connecting miracle: ``L_m`` is realized by a quadratic irrational whose
continued fraction uses only 1s and 2s, and its value is the **Markov value** of
that periodic word — the largest, over all positions, of the forward continued
fraction plus the backward one. Above Freiman's constant (~4.5278) the spectrum
fills a solid ray; in between lies a Cantor-like tangle still under study.
"""

from __future__ import annotations

from fractions import Fraction

from ..cf.core import CF, QuadraticSurd

__all__ = [
    "markov_triples",
    "markov_numbers",
    "lagrange_number",
    "markov_value",
    "extremal_cf",
    "FREIMAN_CONSTANT",
]

# Freiman's constant: the least number above which the Markov spectrum is a full
# ray. Value (2221564096 + 283748*sqrt(462)) / 491993569 ~= 4.5278.
FREIMAN_CONSTANT = 4.527829566711


def markov_triples(limit: int = 1000) -> list[tuple[int, int, int]]:
    """All Markov triples (sorted ascending) with largest entry <= ``limit``.

    Generated by Vieta jumping from ``(1, 1, 1)``.

    >>> markov_triples(30)
    [(1, 1, 1), (1, 1, 2), (1, 2, 5), (1, 5, 13), (2, 5, 29)]
    """
    seen: set[tuple[int, int, int]] = set()
    out: list[tuple[int, int, int]] = []
    stack = [(1, 1, 1)]
    while stack:
        a, b, c = sorted(stack.pop())
        if c > limit or (a, b, c) in seen:
            continue
        seen.add((a, b, c))
        out.append((a, b, c))
        # the three Vieta neighbours (replace one coordinate)
        for na, nb, nc in ((3 * b * c - a, b, c), (a, 3 * a * c - b, c), (a, b, 3 * a * b - c)):
            t = tuple(sorted((na, nb, nc)))
            if min(t) >= 1 and max(t) <= limit and t not in seen:
                stack.append(t)
    out.sort()
    return out


def markov_numbers(limit: int = 1000) -> list[int]:
    """The Markov numbers up to ``limit`` (largest entries of Markov triples).

    >>> markov_numbers(200)
    [1, 2, 5, 13, 29, 34, 89, 169, 194]
    """
    nums = {1, 2}
    for a, b, c in markov_triples(limit):
        nums.add(c)
    return sorted(n for n in nums if n <= limit)


def lagrange_number(m: int) -> QuadraticSurd:
    """The Lagrange number ``L_m = sqrt(9*m^2 - 4) / m`` as an exact surd.

    >>> float(lagrange_number(1))            # sqrt(5)
    2.23606797749979
    >>> lagrange_number(2)                    # sqrt(32)/2 = 2*sqrt(2) = sqrt(8)
    QuadraticSurd(a=Fraction(0, 1), b=Fraction(2, 1), D=2)
    """
    D = 9 * m * m - 4
    return QuadraticSurd.make(0, Fraction(1, m), D)


def _forward(period: list[int], start: int) -> float:
    rot = period[start:] + period[:start]
    return float(CF.periodic([], rot).value())


def _backward(period: list[int], start: int) -> float:
    n = len(period)
    seq = [period[(start - 1 - k) % n] for k in range(n)]
    return float(CF.periodic([0], seq).value())


def markov_value(period: list[int]) -> float:
    """The Markov value of a periodic continued-fraction word.

    Equals ``max_i ( [a_i; a_{i+1}, ...] + [0; a_{i-1}, a_{i-2}, ...] )`` over all
    cyclic positions — the reciprocal of how well the number can be approximated.
    For the Markov words this lands exactly on a Lagrange number.

    >>> round(markov_value([1]), 6)      # golden ratio -> sqrt(5)
    2.236068
    >>> round(markov_value([2]), 6)      # silver ratio -> sqrt(8)
    2.828427
    """
    n = len(period)
    return max(_forward(period, i) + _backward(period, i) for i in range(n))


# Extremal periodic words (in {1, 2}) realizing the first Lagrange numbers.
_EXTREMAL = {1: [1], 2: [2], 5: [2, 2, 1, 1]}


def extremal_cf(m: int) -> list[int] | None:
    """The periodic CF word whose Markov value is ``L_m`` (first few known cases).

    >>> extremal_cf(5)
    [2, 2, 1, 1]
    """
    return list(_EXTREMAL[m]) if m in _EXTREMAL else None
